import { GoogleGenAI } from "@google/genai";

// Ensure API key is present
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.error("Missing API_KEY in environment variables.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Helper to strip the data URL prefix
const stripBase64Prefix = (dataUrl: string): string => {
  return dataUrl.replace(/^data:image\/\w+;base64,/, "");
};

/**
 * Generates a new image based on the source image and the selected era prompt.
 * Uses gemini-2.5-flash-image (Nano Banana).
 */
export const generateTimeTravelImage = async (
  sourceImageBase64: string,
  eraPrompt: string
): Promise<string> => {
  try {
    const cleanBase64 = stripBase64Prefix(sourceImageBase64);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64,
            },
          },
          {
            text: `${eraPrompt} Maintain the facial identity of the person in the image. High resolution, photorealistic masterpiece.`,
          },
        ],
      },
    });

    // Extract the image from the response
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini generation error:", error);
    throw error;
  }
};

/**
 * Edits an existing generated image based on a user's text prompt.
 * Uses gemini-2.5-flash-image.
 */
export const editGeneratedImage = async (
  imageBase64: string,
  userPrompt: string
): Promise<string> => {
  try {
    const cleanBase64 = stripBase64Prefix(imageBase64);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Output from Gemini is usually PNG
              data: cleanBase64,
            },
          },
          {
            text: `Edit this image: ${userPrompt}. Maintain the composition and main subject.`,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No edited image generated.");

  } catch (error) {
    console.error("Gemini edit error:", error);
    throw error;
  }
};